#!/usr/bin/env node
/* Rebuilds the parts of the site search engines read without running
 * JavaScript, straight from js/data.js:
 *
 *   - the trip index in index.html, between the trip-index markers: every
 *     trip as plain text (place, date, blurb and the opening of its story)
 *   - sitemap.xml: the page plus every trip photo
 *   - js/placeholders.js: each photo's loading colours (build-placeholders.py)
 *
 * Run after adding or changing a trip:  node tools/build-seo.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

// the loading colours come first, so a new photo never loads onto a blank box
require('child_process').execFileSync('python3', [path.join(__dirname, 'build-placeholders.py')], { stdio: 'inherit' });
const BASE = 'https://travel.nithinaruswamy.com/';

global.window = {};
require(path.join(ROOT, 'js', 'data.js'));
const TRIPS = window.TRIPS;

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// the first ~240 characters of a story, cut at a word
function opening(trip) {
  const first = (trip.body || []).find((b) => b.p);
  if (!first) return '';
  const text = first.p.trim();
  if (text.length <= 240) return text;
  return text.slice(0, 240).replace(/\s+\S*$/, '') + '…';
}

/* ------------------------------------------------------------ trip index */

const items = TRIPS.map((trip) => {
  const where = trip.place && trip.place !== trip.title ? `${trip.place}, ` : '';
  const blurb = trip.blurb ? ` ${esc(trip.blurb)}.` : '';
  const story = opening(trip);
  return [
    '      <li>',
    `        <h2>${esc(trip.title)}</h2>`,
    `        <p>${esc(where)}${esc(trip.date)}.${blurb}</p>`,
    story ? `        <p>${esc(story)}</p>` : null,
    '      </li>',
  ].filter(Boolean).join('\n');
}).join('\n');

const block = `<!-- trip-index:start (generated by tools/build-seo.js, do not edit by hand) -->
  <section class="trip-index" aria-label="Every trip">
    <h1>Travel with Nithin</h1>
    <p>Photos and stories from 50+ countries by Nithin Aruswamy, author of Jet-Set Teen. Every trip, most recent first.</p>
    <ol>
${items}
    </ol>
  </section>
  <!-- trip-index:end -->`;

const indexPath = path.join(ROOT, 'index.html');
const html = fs.readFileSync(indexPath, 'utf8');
const marked = /<!-- trip-index:start[\s\S]*?<!-- trip-index:end -->/;
if (!marked.test(html)) throw new Error('trip-index markers missing from index.html');
fs.writeFileSync(indexPath, html.replace(marked, block));

/* --------------------------------------------------------------- sitemap */

const images = [...new Set(TRIPS.flatMap((t) =>
  [t.image, ...(t.body || []).filter((b) => b.img).map((b) => b.img)]))];
const missing = images.filter((i) => !fs.existsSync(path.join(ROOT, i)));
if (missing.length) throw new Error('missing photos: ' + missing.join(', '));

const today = new Date().toISOString().slice(0, 10);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <url>
    <loc>${BASE}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
${images.map((i) => `    <image:image><image:loc>${esc(BASE + i)}</image:loc></image:image>`).join('\n')}
  </url>
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);

console.log(`trip index: ${TRIPS.length} trips · sitemap: ${images.length} photos`);
