#!/usr/bin/env python3
"""Works out a two-tone placeholder for every photo on the site and writes
them to js/placeholders.js. While a photo loads, its frame shows a soft
gradient in the photo's own colours (a lighter top, a deeper bottom) instead
of an empty box. See setPhoto() in js/app.js.

Run by tools/build-seo.js, or on its own:  python3 tools/build-placeholders.py
"""
import colorsys, json, os, re

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def photos():
    """Every image path the site references: data.js plus the about photo."""
    data = open(os.path.join(ROOT, 'js', 'data.js')).read()
    found = re.findall(r'"(?:image|img|photo)":\s*"([^"]+)"', data)
    return sorted(set(found))


def tones(path):
    """A pastel of the photo's most vivid colour, lighter above, deeper below."""
    im = Image.open(os.path.join(ROOT, path)).convert('RGB')
    im.thumbnail((160, 160))
    quantized = im.quantize(colors=10, method=Image.MEDIANCUT)
    palette = quantized.getpalette()
    best = None
    for count, index in quantized.getcolors():
        r, g, b = (c / 255 for c in palette[index * 3:index * 3 + 3])
        h, s, v = colorsys.rgb_to_hsv(r, g, b)
        if v < 0.2:
            continue
        score = count * s ** 1.6
        if best is None or score > best[0]:
            best = (score, h, s)
    _, h, s = best or (0, 0, 0)
    # a black-and-white (or nearly colourless) photo gets a neutral grey
    # rather than a tint picked out of its noise
    s = 0 if s < 0.12 else min(max(s * 1.25, 0.18), 0.5)

    def hex_of(sat, val):
        return '#%02x%02x%02x' % tuple(round(c * 255) for c in colorsys.hsv_to_rgb(h, sat, val))

    return [hex_of(s * 0.7, 0.95), hex_of(s, 0.84)]


table = {path: tones(path) for path in photos()}
with open(os.path.join(ROOT, 'js', 'placeholders.js'), 'w') as out:
    out.write('/* Generated by tools/build-placeholders.py: the loading colours for\n'
              '   every photo, [top, bottom]. Do not edit by hand. */\n')
    out.write('window.PLACEHOLDERS = {\n')
    out.write(',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in sorted(table.items())))
    out.write('\n};\n')
print(f'placeholders: {len(table)} photos')
